Section "InputClass"
        Identifier "Synaptics pointer inertia"
        MatchIsTouchpad "on"
        Driver "synaptics"
        Option "PointerInertia" "on"
        Option "PointerInertiaMinVelocity" "3.1"
        Option "PointerInertiaStartMultiplier" "0.88"
        Option "PointerInertiaDecayTime" "1658"
        Option "PointerInertiaStopVelocity" "1.9"
        Option "PointerInertiaMinDistance" "0.75"
        Option "PointerInertiaLiftTailRatio" "0.45"
        Option "PointerInertiaMinTouchTime" "50"
        Option "PointerInertiaVelocityStaleTime" "150"
        Option "PointerInertiaStopTouchTime" "24"
        Option "PointerInertiaRetouchArmTime" "200"
        Option "PointerInertiaMaxDuration" "0"
        Option "PointerInertiaVelocitySamples" "8"
        Option "PointerInertiaTailSamples" "10"
        Option "PointerInertiaRestartAfterStop" "on"
        Option "PointerInertiaEdgeScrollExit" "on"
        Option "PointerInertiaClickGenTapTime" "128"
        Option "PointerInertiaDebug" "off"
EndSection
