Section "InputClass"
        Identifier "Synaptics pointer inertia"
        MatchIsTouchpad "on"
        Driver "synaptics"
        Option "PointerInertia" "on"
        Option "PointerInertiaMinVelocity" "7.7"
        Option "PointerInertiaStartMultiplier" "1.3"
        Option "PointerInertiaDecayTime" "1658"
        Option "PointerInertiaStopVelocity" "1.9"
        Option "PointerInertiaMinDistance" "3.1"
        Option "PointerInertiaLiftTailRatio" "0.45"
        Option "PointerInertiaMinTouchTime" "130"
        Option "PointerInertiaVelocityStaleTime" "150"
        Option "PointerInertiaStopTouchTime" "56"
        Option "PointerInertiaRetouchArmTime" "200"
        Option "PointerInertiaMaxDuration" "0"
        Option "PointerInertiaVelocitySamples" "8"
        Option "PointerInertiaTailSamples" "10"
        Option "PointerInertiaDebug" "off"
EndSection
